# Implement your procedural solution here!

# - Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#     - 1,2,3,5,8,13,21,34,55,89...
# - By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def even_fibonacci_sum(limit)
  arr = [1, 2]
  while arr[arr.length-1] < limit
    value = (arr[arr.length-2] + arr[arr.length-1])
      if value < limit
       arr.push(value)
     else
       break
      end
  end
   sum = 0
   arr.each do |num|
     if num%2 == 0
       sum += num
     end
   end
   sum
end
